#Which component should be more used (RAM or CPU)
componentUsage: CPU

#Should player data be saved in database or yaml file
database: false

#Database settings
#Available database types
#MariaDB
#PostgreSQL
#H2
#OracleDB
sqlSettings:
  user: user
  password: passwrd
  host: localhost
  port: 3306
  database: simpleDatabase
  type: MariaDB

#Should players be able to enable auto sell function
autoSellEnabled: true

#Should server count amount of blocks mined by players
countingBlocksEnabled: true

#Should players be able to use sell all function
sellAllEnabled: true

#Should blocks be counted only if broken with "miningTools"
countOnlyOnMiningTools: false

#Should plugin ignore world guard
ignoreWorldGuard: false

#Drop to inventory
dropToInventory: true

miningTools:
  - WOODEN_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - DIAMOND_PICKAXE


#What ores should dropped when mined with autosell or dropToInventory enabled
oreDrops:
  COAL_ORE: COAL
  EMERALD_ORE: EMERALD
  IRON_ORE: IRON_INGOT
  GOLD_ORE: GOLD_INGOT
  DIAMOND_ORE: DIAMOND

#Used to count dropped items while autosell or dropToInventory is enabled
fortuneDrops:
  1:
    min: 1
    max: 2
  2:
    min: 1
    max: 3
  3:
    min: 1
    max: 5

#Minepacks
minepacks:
  #Should items be sold from backpacks
  sellFromBackpack: true