name: AutoSell
authors:
  - Pijok
  - FezMLG
version: 1.0.0
main: pl.pijok.autosell.AutoSell
description: Allow players to automaticly sell mined blocks.
api-version: 1.13
softdepend:
  - WorldGuard
  - Vault
  - PlaceholderAPI
commands:
  autosell:
    usage: /autosell
    description: Used to enable or disable autosell function
  sellall:
    usage: /sellall
    description: Used to sell all items from inventory
  adminautosell:
    usage: /adminautosell
    description: Admin command for managing autosell plugin
    aliases:
      - aas
      - aautosell